version: '3.3'

services:

  database:
    image: redis


  server:
    build: ./server
    volumes:
      - ./server:/app

    command:
      - "[python, main.py]"
    environment:
      - SMTP_HOST=0.0.0.0
      - SMTP_PORT=4467
    depends_on:
      - database