version: '3.3'

services:

  database:
    image: redis


  smtp_server:
    build: smtp_server
    volumes:
      - ./smtp_server:/app

    command: python main.py
    environment:
      - DOMAIN=test
      - TLD=com
      - SMTP_HOST=0.0.0.0
      - SMTP_PORT=8025
    depends_on:
      - database