"""remove delete cascade

Revision ID: 0d59459c51c9
Revises: 47467be3edcb
Create Date: 2022-06-28 17:27:35.256898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d59459c51c9'
down_revision = '47467be3edcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_emails_emails_id_fkey', 'user_emails', type_='foreignkey')
    op.drop_constraint('user_emails_user_uuid_fkey', 'user_emails', type_='foreignkey')
    op.create_foreign_key(None, 'user_emails', 'users', ['user_uuid'], ['uuid'])
    op.create_foreign_key(None, 'user_emails', 'emails', ['emails_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_emails', type_='foreignkey')
    op.drop_constraint(None, 'user_emails', type_='foreignkey')
    op.create_foreign_key('user_emails_user_uuid_fkey', 'user_emails', 'users', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key('user_emails_emails_id_fkey', 'user_emails', 'emails', ['emails_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
