"""as_uuid=True for user_uuid col of UserEmails

Revision ID: 4496901bb5a0
Revises: 20001b1a9f22
Create Date: 2022-06-27 12:24:38.048725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4496901bb5a0'
down_revision = '20001b1a9f22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
