"""Added datetime col for emails

Revision ID: 47467be3edcb
Revises: e5334c30fd32
Create Date: 2022-06-28 17:17:20.840022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47467be3edcb'
down_revision = 'e5334c30fd32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'datetime')
    # ### end Alembic commands ###
