"""message renamed to body, nullable=True

Revision ID: 85fe3e197a58
Revises: dbe866a23c0e
Create Date: 2022-06-27 21:58:25.505608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fe3e197a58'
down_revision = 'dbe866a23c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('emails', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('emails', 'body')
    # ### end Alembic commands ###
