"""UserEmails UUID to string

Revision ID: d9394084277a
Revises: 4496901bb5a0
Create Date: 2022-06-27 12:30:43.752246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9394084277a'
down_revision = '4496901bb5a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
