"""emails subject nullable=True

Revision ID: d9845bc89270
Revises: d9394084277a
Create Date: 2022-06-27 12:44:24.360050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9845bc89270'
down_revision = 'd9394084277a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'subject',
               existing_type=sa.VARCHAR(length=70),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'subject',
               existing_type=sa.VARCHAR(length=70),
               nullable=False)
    # ### end Alembic commands ###
