"""name fields - Users

Revision ID: 1627794be625
Revises: 56c0232727e1
Create Date: 2022-08-10 10:43:51.414119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1627794be625'
down_revision = '56c0232727e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=40), nullable=False, server_default=""))
    op.add_column('users', sa.Column('surname', sa.String(length=40), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
