"""Create after_update event

Revision ID: 197adcc2adaa
Revises: 0d59459c51c9
Create Date: 2022-06-28 19:35:57.534589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197adcc2adaa'
down_revision = '0d59459c51c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
