"""as_uuid=False on uuid col of Users

Revision ID: 2351ccf1545f
Revises: b51db325c689
Create Date: 2022-07-05 17:51:16.014126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2351ccf1545f'
down_revision = 'b51db325c689'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=70), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('retrieved', sa.Boolean(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('user_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), nullable=True),
    sa.Column('emails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emails_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_emails')
    op.drop_table('users')
    op.drop_table('emails')
    # ### end Alembic commands ###
