"""renamed users field of Emails to recipients

Revision ID: 33e47023def7
Revises: 2351ccf1545f
Create Date: 2022-07-05 20:17:10.484792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e47023def7'
down_revision = '2351ccf1545f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
