"""backup field to Emails

Revision ID: 56c0232727e1
Revises: a85ff44cb838
Create Date: 2022-08-07 22:10:32.653029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c0232727e1'
down_revision = 'a85ff44cb838'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('backup', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'backup')
    # ### end Alembic commands ###
