"""ENUM name

Revision ID: a85ff44cb838
Revises: e2ede5ea27cd
Create Date: 2022-07-26 23:04:13.246591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a85ff44cb838'
down_revision = 'e2ede5ea27cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=70), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('retrieved', sa.Boolean(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('folder', postgresql.ENUM('Inbox', 'Archived', 'Trash', name='folder_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('user_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), nullable=True),
    sa.Column('emails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emails_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_emails')
    op.drop_table('users')
    op.drop_table('emails')
    # ### end Alembic commands ###
