"""UserEmails user_uuid of uuid type

Revision ID: b51db325c689
Revises: 197adcc2adaa
Create Date: 2022-07-01 21:59:57.531450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51db325c689'
down_revision = '197adcc2adaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
