"""ARRAY type for emails recipients

Revision ID: dbe866a23c0e
Revises: d9845bc89270
Create Date: 2022-06-27 13:28:14.944956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe866a23c0e'
down_revision = 'd9845bc89270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
